baseURL = "https://xiegerts.com/"
languageCode = "en-us"
title = "xiegerts"
theme ="hugo-theme-basic"

googleAnalytics = "UA-134038089-1"
copyright = ""

publishDir = "docs"

[params]
    twitter = "siegerts"


[Permalinks]
  post = "post/:slug"

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = true
  [privacy.twitter]
    enableDNT = true
  [privacy.youtube]
    privacyEnhanced = true