baseURL = "https://xiegerts.com/"
languageCode = "en-us"
title = "xiegerts"
theme ="hugo-theme-basic"
enableEmoji = true 

GoogleAnalytics = "UA-134038089-1"
copyright = "© 2016-19 S. Siegert"


[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[params]
  titleEmoji = ":coffee: :dog:"
  twitter = "siegerts"

[Permalinks]
  blog = "blog/:slug"

# links
[[params.menu]]
  name = "blog"
  url = "blog/"

[[params.menu]]
  name = "github"
  url = "https://github.com/siegerts"

[[params.menu]]
  name = "gitlab"
  url = "https://gitlab.com/siegerts"


[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = true
  [privacy.twitter]
    enableDNT = true
  [privacy.youtube]
    privacyEnhanced = true