baseurl = "https://edwww.com"
languageCode = "en-us"
title = "老登纪"
theme = ["flexible-seo-hugo"]
googleAnalytics = ""
enableRobotsTXT = true
disableHugoGeneratorInject = true
pluralizelisttitles = false

[markup.goldmark.renderer]
unsafe = true

[Params]
  description = "Personal website of DAN's; 老登纪"
  schemas = []
  page_schemas = []
  seo = []
  homeType = "simple"
  navType = "simple"
  headerType = "simple"
  taxonomyHeaderType = "simple"
  footerType = "bar_with_2_columns"

[taxonomies]

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true

